import React, { MouseEventHandler, useEffect, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux';

import styles from '../styles/Home.module.css'
import { increment } from '../app/redux/counter/counterSlice';
import { AppDispatch } from '../app/store';

const Home: NextPage = () => {
  const dispatch: AppDispatch = useDispatch();

  const [message, setMessage] = useState('');

  const sendFindAll: MouseEventHandler<HTMLAnchorElement> = (e) => {
    e.preventDefault();

    dispatch(increment());
  }

  const sendMessage: MouseEventHandler<HTMLAnchorElement> = () => {

  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Connected: да
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card} onClick={sendFindAll}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>

        <div className={styles.grid}>
          <input
            type="text"
            placeholder="Enter message"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
          />

          <button onClick={() => console.log('send')}>Send</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
