import React, { MouseEventHandler, useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch } from 'react-redux';

import styles from '../styles/home.module.css'
import { AppDispatch } from '../app/store';
import { loginAsync } from '../app/domen/facebook/facebook.slice';

const Home: NextPage = () => {
  const dispatch: AppDispatch = useDispatch();

  const [message, setMessage] = useState('');

  const onLogin: MouseEventHandler<HTMLButtonElement> = (e) => {
    e.preventDefault();

    dispatch(loginAsync());
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Connected: да
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <input
            type="text"
            placeholder="Enter message"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
          />

          <a href="http://localhost:3000/facebook">login</a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
